modLoader="javafml"
loaderVersion="[66,)"
license="GPL-3.0-only"

[[mods]]
modId="adventurers"
version="0.3.0"
displayName="冒险人 · Adventurers"
authors="xzh-minecraft-server"
description='''文明演化与符文实验模组。统一主循环驱动气候、生命、城邦与玩家的冒险。'''

[[dependencies.adventurers]]
modId="forge"
mandatory=true
versionRange="[66.0.9,67)"
ordering="NONE"
side="BOTH"

[[dependencies.adventurers]]
modId="minecraft"
mandatory=true
versionRange="[26.3,26.4)"
ordering="NONE"
side="BOTH"
